"""Data for the Common Emojis feature."""

# A curated list of common emojis with keywords for searching
EMOJI_DATA = [
    # Faces
    {"char": "😀", "name": "grinning face", "keywords": ["smile", "happy", "joy", "grin"]},
    {"char": "😃", "name": "grinning face with big eyes", "keywords": ["smile", "happy", "joy", "excited"]},
    {"char": "😄", "name": "grinning face with smiling eyes", "keywords": ["smile", "happy", "joy"]},
    {"char": "😂", "name": "face with tears of joy", "keywords": ["laugh", "cry", "happy", "lol", "lmao"]},
    {"char": "🤣", "name": "rolling on the floor laughing", "keywords": ["laugh", "rofl", "lol", "lmao"]},
    {"char": "🙂", "name": "slightly smiling face", "keywords": ["smile", "happy", "okay"]},
    {"char": "🙃", "name": "upside-down face", "keywords": ["silly", "sarcasm", "irony"]},
    {"char": "😉", "name": "winking face", "keywords": ["wink", "flirt", "joke"]},
    {"char": "😊", "name": "smiling face with smiling eyes", "keywords": ["smile", "happy", "blush"]},
    {"char": "😇", "name": "smiling face with halo", "keywords": ["angel", "good", "innocent"]},
    {"char": "🥰", "name": "smiling face with hearts", "keywords": ["love", "crush", "adore"]},
    {"char": "😍", "name": "smiling face with heart-eyes", "keywords": ["love", "crush", "adore", "beautiful"]},
    {"char": "🤩", "name": "star-struck", "keywords": ["excited", "star", "wow", "amazing"]},
    {"char": "😘", "name": "face blowing a kiss", "keywords": ["kiss", "love", "flirt"]},
    {"char": "😋", "name": "face savoring food", "keywords": ["yum", "tasty", "delicious", "tongue"]},
    {"char": "🤪", "name": "zany face", "keywords": ["silly", "crazy", "goofy"]},
    {"char": "😐", "name": "neutral face", "keywords": ["meh", "okay", "straight", "poker"]},
    {"char": "😑", "name": "expressionless face", "keywords": ["meh", "okay", "straight", "poker"]},
    {"char": "🤔", "name": "thinking face", "keywords": ["think", "hmm", "idea", "wonder"]},
    {"char": "🤫", "name": "shushing face", "keywords": ["shh", "quiet", "silence", "secret"]},
    {"char": "🙄", "name": "face with rolling eyes", "keywords": ["eyeroll", "annoyed", "whatever", "sarcasm"]},
    {"char": "😬", "name": "grimacing face", "keywords": ["awkward", "oops", "nervous"]},
    {"char": "🤥", "name": "lying face", "keywords": ["lie", "pinocchio", "fake"]},
    {"char": "😌", "name": "relieved face", "keywords": ["calm", "zen", "peace"]},
    {"char": "😔", "name": "pensive face", "keywords": ["sad", "thoughtful", "sorry"]},
    {"char": "😪", "name": "sleepy face", "keywords": ["sleep", "tired", "zzz"]},
    {"char": "🤤", "name": "drooling face", "keywords": ["hungry", "desire", "sleep"]},
    {"char": "😴", "name": "sleeping face", "keywords": ["sleep", "tired", "zzz", "dream"]},
    {"char": "😷", "name": "face with medical mask", "keywords": ["sick", "ill", "mask", "doctor"]},
    {"char": "🤒", "name": "face with thermometer", "keywords": ["sick", "ill", "fever"]},
    {"char": "🤕", "name": "face with head-bandage", "keywords": ["hurt", "injured", "pain"]},
    {"char": "🤢", "name": "nauseated face", "keywords": ["sick", "vomit", "green"]},
    {"char": "🤮", "name": "face vomiting", "keywords": ["sick", "vomit", "puke"]},
    {"char": "🤧", "name": "sneezing face", "keywords": ["sneeze", "sick", "allergy"]},
    {"char": "🥵", "name": "hot face", "keywords": ["hot", "sweat", "heat"]},
    {"char": "🥶", "name": "cold face", "keywords": ["cold", "freeze", "ice"]},
    {"char": "🥴", "name": "woozy face", "keywords": ["drunk", "dizzy", "confused"]},
    {"char": "😵", "name": "dizzy face", "keywords": ["dizzy", "dead", "confused"]},
    {"char": "🤯", "name": "exploding head", "keywords": ["mindblown", "wow", "shock"]},
    {"char": "🤠", "name": "cowboy hat face", "keywords": ["cowboy", "yeehaw", "western"]},
    {"char": "🥳", "name": "partying face", "keywords": ["party", "celebrate", "woohoo"]},
    {"char": "😎", "name": "smiling face with sunglasses", "keywords": ["cool", "shades", "sunglasses"]},
    {"char": "🤓", "name": "nerd face", "keywords": ["nerd", "geek", "smart", "glasses"]},
    {"char": "🧐", "name": "face with monocle", "keywords": ["fancy", "investigate", "hmm"]},
    {"char": "😕", "name": "confused face", "keywords": ["confused", "what", "huh"]},
    {"char": "😟", "name": "worried face", "keywords": ["worry", "sad", "concern"]},
    {"char": "😮", "name": "face with open mouth", "keywords": ["wow", "surprise", "omg"]},
    {"char": "😯", "name": "hushed face", "keywords": ["quiet", "surprise", "speechless"]},
    {"char": "😲", "name": "astonished face", "keywords": ["shock", "wow", "omg"]},
    {"char": "😳", "name": "flushed face", "keywords": ["embarrassed", "blush", "shock"]},
    {"char": "🥺", "name": "pleading face", "keywords": ["please", "beg", "puppy eyes", "sad"]},
    {"char": "😦", "name": "frowning face with open mouth", "keywords": ["sad", "surprise", "fear"]},
    {"char": "😧", "name": "anguished face", "keywords": ["pain", "fear", "worry"]},
    {"char": "😨", "name": "fearful face", "keywords": ["scared", "fear", "afraid"]},
    {"char": "😰", "name": "anxious face with sweat", "keywords": ["nervous", "sweat", "worry"]},
    {"char": "😥", "name": "sad but relieved face", "keywords": ["phew", "sweat", "relief"]},
    {"char": "😢", "name": "crying face", "keywords": ["cry", "sad", "tear"]},
    {"char": "😭", "name": "loudly crying face", "keywords": ["cry", "sad", "sob", "tears"]},
    {"char": "😱", "name": "face screaming in fear", "keywords": ["scream", "scared", "fear", "horror"]},
    {"char": "😖", "name": "confounded face", "keywords": ["frustrated", "annoyed", "pain"]},
    {"char": "😣", "name": "persevering face", "keywords": ["struggle", "pain", "effort"]},
    {"char": "😞", "name": "disappointed face", "keywords": ["sad", "sorry", "fail"]},
    {"char": "😓", "name": "downcast face with sweat", "keywords": ["sweat", "worry", "tired"]},
    {"char": "😩", "name": "weary face", "keywords": ["tired", "exhausted", "whine"]},
    {"char": "😫", "name": "tired face", "keywords": ["tired", "exhausted", "sleepy"]},
    {"char": "🥱", "name": "yawning face", "keywords": ["yawn", "tired", "boring"]},
    {"char": "😤", "name": "face with steam from nose", "keywords": ["angry", "mad", "fume"]},
    {"char": "😡", "name": "pouting face", "keywords": ["angry", "mad", "red"]},
    {"char": "😠", "name": "angry face", "keywords": ["angry", "mad", "annoyed"]},
    {"char": "🤬", "name": "face with symbols on mouth", "keywords": ["swear", "curse", "angry", "mad"]},
    {"char": "😈", "name": "smiling face with horns", "keywords": ["devil", "evil", "naughty"]},
    {"char": "👿", "name": "angry face with horns", "keywords": ["devil", "evil", "angry"]},
    {"char": "💀", "name": "skull", "keywords": ["death", "dead", "skeleton"]},
    {"char": "💩", "name": "pile of poo", "keywords": ["poop", "shit", "crap"]},
    {"char": "🤡", "name": "clown face", "keywords": ["clown", "silly", "creepy"]},
    {"char": "👻", "name": "ghost", "keywords": ["spooky", "halloween", "boo"]},
    {"char": "👽", "name": "alien", "keywords": ["ufo", "space", "et"]},
    {"char": "🤖", "name": "robot", "keywords": ["bot", "ai", "machine"]},

    # Hand Gestures
    {"char": "👋", "name": "waving hand", "keywords": ["wave", "hello", "hi", "bye"]},
    {"char": "🤚", "name": "raised back of hand", "keywords": ["stop", "high five", "hand"]},
    {"char": "🖐️", "name": "hand with fingers splayed", "keywords": ["hand", "five", "stop"]},
    {"char": "✋", "name": "raised hand", "keywords": ["stop", "high five", "hand"]},
    {"char": "🖖", "name": "vulcan salute", "keywords": ["startrek", "spock", "live long"]},
    {"char": "👌", "name": "OK hand", "keywords": ["ok", "perfect", "good"]},
    {"char": "🤌", "name": "pinched fingers", "keywords": ["italian", "chef kiss", "what"]},
    {"char": "🤏", "name": "pinching hand", "keywords": ["tiny", "small", "little"]},
    {"char": "✌️", "name": "victory hand", "keywords": ["peace", "two", "victory"]},
    {"char": "🤞", "name": "crossed fingers", "keywords": ["luck", "hope", "cross"]},
    {"char": "🤟", "name": "love-you gesture", "keywords": ["love", "rock", "metal"]},
    {"char": "🤘", "name": "sign of the horns", "keywords": ["rock", "metal", "devil"]},
    {"char": "🤙", "name": "call me hand", "keywords": ["call", "phone", "cool", "hang loose"]},
    {"char": "👈", "name": "backhand index pointing left", "keywords": ["left", "point", "direction"]},
    {"char": "👉", "name": "backhand index pointing right", "keywords": ["right", "point", "direction"]},
    {"char": "👆", "name": "backhand index pointing up", "keywords": ["up", "point", "direction"]},
    {"char": "🖕", "name": "middle finger", "keywords": ["rude", "fuck", "offense"]},
    {"char": "👇", "name": "backhand index pointing down", "keywords": ["down", "point", "direction"]},
    {"char": "👍", "name": "thumbs up", "keywords": ["yes", "like", "approve", "good"]},
    {"char": "👎", "name": "thumbs down", "keywords": ["no", "dislike", "bad"]},
    {"char": "👊", "name": "oncoming fist", "keywords": ["fist", "punch", "brofist"]},
    {"char": "🤛", "name": "left-facing fist", "keywords": ["fist", "punch"]},
    {"char": "🤜", "name": "right-facing fist", "keywords": ["fist", "punch"]},
    {"char": "👏", "name": "clapping hands", "keywords": ["clap", "applause", "bravo"]},
    {"char": "🙌", "name": "raising hands", "keywords": ["celebrate", "praise", "hands"]},
    {"char": "👐", "name": "open hands", "keywords": ["open", "hug", "jazz hands"]},
    {"char": "🤲", "name": "palms up together", "keywords": ["pray", "beg", "open"]},
    {"char": "🤝", "name": "handshake", "keywords": ["shake", "deal", "agree"]},
    {"char": "🙏", "name": "folded hands", "keywords": ["pray", "please", "thanks", "namaste"]},

    # Hearts & Symbols
    {"char": "❤️", "name": "red heart", "keywords": ["love", "heart", "like"]},
    {"char": "🧡", "name": "orange heart", "keywords": ["love", "heart", "like"]},
    {"char": "💛", "name": "yellow heart", "keywords": ["love", "heart", "like"]},
    {"char": "💚", "name": "green heart", "keywords": ["love", "heart", "like", "nature"]},
    {"char": "💙", "name": "blue heart", "keywords": ["love", "heart", "like"]},
    {"char": "💜", "name": "purple heart", "keywords": ["love", "heart", "like"]},
    {"char": "🖤", "name": "black heart", "keywords": ["love", "heart", "like", "dark"]},
    {"char": "🤍", "name": "white heart", "keywords": ["love", "heart", "like"]},
    {"char": "🤎", "name": "brown heart", "keywords": ["love", "heart", "like"]},
    {"char": "💔", "name": "broken heart", "keywords": ["break", "sad", "heart"]},
    {"char": "❣️", "name": "heart exclamation", "keywords": ["love", "heart", "exclamation"]},
    {"char": "💕", "name": "two hearts", "keywords": ["love", "hearts", "pink"]},
    {"char": "💞", "name": "revolving hearts", "keywords": ["love", "hearts", "pink"]},
    {"char": "💓", "name": "beating heart", "keywords": ["love", "heart", "beat"]},
    {"char": "💗", "name": "growing heart", "keywords": ["love", "heart", "grow"]},
    {"char": "💖", "name": "sparkling heart", "keywords": ["love", "heart", "sparkle"]},
    {"char": "💘", "name": "heart with arrow", "keywords": ["love", "heart", "cupid"]},
    {"char": "💝", "name": "heart with ribbon", "keywords": ["love", "heart", "gift"]},
    {"char": "💯", "name": "hundred points", "keywords": ["100", "score", "perfect"]},
    {"char": "💢", "name": "anger symbol", "keywords": ["angry", "mad", "vein"]},
    {"char": "💥", "name": "collision", "keywords": ["boom", "explode", "crash"]},
    {"char": "💫", "name": "dizzy", "keywords": ["star", "sparkle", "dizzy"]},
    {"char": "💦", "name": "sweat droplets", "keywords": ["water", "sweat", "wet"]},
    {"char": "💨", "name": "dashing away", "keywords": ["run", "fast", "wind"]},
    {"char": "💤", "name": "zzz", "keywords": ["sleep", "snore", "tired"]},

    # Animals & Nature
    {"char": "🐶", "name": "dog face", "keywords": ["dog", "puppy", "pet", "animal"]},
    {"char": "🐱", "name": "cat face", "keywords": ["cat", "kitten", "pet", "animal"]},
    {"char": "🐭", "name": "mouse face", "keywords": ["mouse", "rodent", "animal"]},
    {"char": "🐹", "name": "hamster face", "keywords": ["hamster", "pet", "animal"]},
    {"char": "🐰", "name": "rabbit face", "keywords": ["rabbit", "bunny", "animal"]},
    {"char": "🦊", "name": "fox", "keywords": ["fox", "animal"]},
    {"char": "🐻", "name": "bear", "keywords": ["bear", "animal"]},
    {"char": "🐼", "name": "panda", "keywords": ["panda", "animal"]},
    {"char": "🐨", "name": "koala", "keywords": ["koala", "animal"]},
    {"char": "🐯", "name": "tiger face", "keywords": ["tiger", "animal"]},
    {"char": "🦁", "name": "lion", "keywords": ["lion", "animal", "king"]},
    {"char": "🐮", "name": "cow face", "keywords": ["cow", "animal"]},
    {"char": "🐷", "name": "pig face", "keywords": ["pig", "animal"]},
    {"char": "🐸", "name": "frog", "keywords": ["frog", "animal"]},
    {"char": "🐵", "name": "monkey face", "keywords": ["monkey", "animal"]},
    {"char": "🐔", "name": "chicken", "keywords": ["chicken", "bird", "animal"]},
    {"char": "🐧", "name": "penguin", "keywords": ["penguin", "bird", "animal"]},
    {"char": "🐦", "name": "bird", "keywords": ["bird", "animal"]},
    {"char": "🐤", "name": "baby chick", "keywords": ["chick", "bird", "animal"]},
    {"char": "🦆", "name": "duck", "keywords": ["duck", "bird", "animal"]},
    {"char": "🦅", "name": "eagle", "keywords": ["eagle", "bird", "animal"]},
    {"char": "🦉", "name": "owl", "keywords": ["owl", "bird", "animal"]},
    {"char": "🦇", "name": "bat", "keywords": ["bat", "animal"]},
    {"char": "🐺", "name": "wolf", "keywords": ["wolf", "animal"]},
    {"char": "🐗", "name": "boar", "keywords": ["boar", "animal"]},
    {"char": "🐴", "name": "horse face", "keywords": ["horse", "animal"]},
    {"char": "🦄", "name": "unicorn", "keywords": ["unicorn", "fantasy", "animal"]},
    {"char": "🐝", "name": "honeybee", "keywords": ["bee", "insect", "animal"]},
    {"char": "🐛", "name": "bug", "keywords": ["caterpillar", "insect", "animal"]},
    {"char": "🦋", "name": "butterfly", "keywords": ["butterfly", "insect", "animal"]},
    {"char": "🐌", "name": "snail", "keywords": ["snail", "animal"]},
    {"char": "💐", "name": "bouquet", "keywords": ["flowers", "gift", "nature"]},
    {"char": "🌸", "name": "cherry blossom", "keywords": ["flower", "pink", "nature"]},
    {"char": "💮", "name": "white flower", "keywords": ["flower", "white", "nature"]},
    {"char": "🌹", "name": "rose", "keywords": ["flower", "red", "love"]},
    {"char": "🌺", "name": "hibiscus", "keywords": ["flower", "pink", "tropical"]},
    {"char": "🌻", "name": "sunflower", "keywords": ["flower", "yellow", "sun"]},
    {"char": "🌼", "name": "blossom", "keywords": ["flower", "yellow", "nature"]},
    {"char": "🌷", "name": "tulip", "keywords": ["flower", "spring", "nature"]},
    {"char": "🌱", "name": "seedling", "keywords": ["plant", "grow", "nature"]},
    {"char": "🌲", "name": "evergreen tree", "keywords": ["tree", "forest", "nature"]},
    {"char": "🌳", "name": "deciduous tree", "keywords": ["tree", "forest", "nature"]},
    {"char": "🌴", "name": "palm tree", "keywords": ["tree", "tropical", "beach"]},
    {"char": "🌵", "name": "cactus", "keywords": ["plant", "desert", "nature"]},
    {"char": "🍄", "name": "mushroom", "keywords": ["fungus", "toadstool", "nature"]},

    # Objects
    {"char": "🔥", "name": "fire", "keywords": ["hot", "burn", "flame", "lit"]},
    {"char": "✨", "name": "sparkles", "keywords": ["shine", "clean", "magic"]},
    {"char": "⭐", "name": "star", "keywords": ["yellow", "sky", "rate"]},
    {"char": "🌟", "name": "glowing star", "keywords": ["shine", "sparkle", "rate"]},
    {"char": "⚡", "name": "high voltage", "keywords": ["lightning", "thunder", "electric"]},
    {"char": "💡", "name": "light bulb", "keywords": ["idea", "bright", "electric"]},
    {"char": "💣", "name": "bomb", "keywords": ["explode", "boom", "weapon"]},
    {"char": "🎉", "name": "party popper", "keywords": ["celebrate", "congrats", "party"]},
    {"char": "🎊", "name": "confetti ball", "keywords": ["celebrate", "party", "ball"]},
    {"char": "🎈", "name": "balloon", "keywords": ["party", "celebrate", "birthday"]},
    {"char": "🎂", "name": "birthday cake", "keywords": ["birthday", "cake", "food", "party"]},
    {"char": "🎁", "name": "wrapped gift", "keywords": ["present", "box", "birthday"]},
    {"char": "🏆", "name": "trophy", "keywords": ["win", "prize", "award"]},
    {"char": "🏅", "name": "sports medal", "keywords": ["win", "gold", "award"]},
    {"char": "🥇", "name": "1st place medal", "keywords": ["win", "gold", "award"]},
    {"char": "💎", "name": "gem stone", "keywords": ["diamond", "jewel", "rich"]},
    {"char": "💰", "name": "money bag", "keywords": ["dollar", "cash", "rich"]},
    {"char": "💸", "name": "money with wings", "keywords": ["dollar", "fly", "spend"]},
    {"char": "💵", "name": "dollar banknote", "keywords": ["money", "cash", "usa"]},
    {"char": "💶", "name": "euro banknote", "keywords": ["money", "cash", "europe"]},
    {"char": "💷", "name": "pound banknote", "keywords": ["money", "cash", "uk"]},
    {"char": "💻", "name": "laptop", "keywords": ["computer", "tech", "work"]},
    {"char": "📱", "name": "mobile phone", "keywords": ["cell", "tech", "call"]},
    {"char": "📸", "name": "camera_with_flash", "keywords": ["photo", "pic", "picture"]},
    {"char": "🎥", "name": "movie camera", "keywords": ["video", "film", "cinema"]},
    {"char": "📞", "name": "telephone receiver", "keywords": ["phone", "call"]},
    {"char": "🔍", "name": "magnifying glass tilted left", "keywords": ["search", "find", "zoom"]},
    {"char": "🔎", "name": "magnifying glass tilted right", "keywords": ["search", "find", "zoom"]},
    {"char": "🔒", "name": "locked", "keywords": ["security", "padlock", "closed"]},
    {"char": "🔓", "name": "unlocked", "keywords": ["security", "padlock", "open"]},
    {"char": "🖊️", "name": "pen", "keywords": ["write", "stationery"]},
    {"char": "📝", "name": "memo", "keywords": ["write", "note", "paper"]},
    {"char": "📅", "name": "calendar", "keywords": ["date", "schedule"]},
    {"char": "📌", "name": "pushpin", "keywords": ["pin", "marker", "location"]},
    {"char": "📍", "name": "round pushpin", "keywords": ["pin", "marker", "location"]},
    {"char": "✂️", "name": "scissors", "keywords": ["cut", "tool"]},
    {"char": "🗑️", "name": "wastebasket", "keywords": ["trash", "bin", "garbage"]},

    # Checkmarks & Symbols
    {"char": "✅", "name": "check mark button", "keywords": ["yes", "correct", "done", "green"]},
    {"char": "☑️", "name": "check box with check", "keywords": ["yes", "correct", "done"]},
    {"char": "✔️", "name": "check mark", "keywords": ["yes", "correct", "done"]},
    {"char": "❌", "name": "cross mark", "keywords": ["no", "wrong", "delete", "red"]},
    {"char": "❎", "name": "cross mark button", "keywords": ["no", "wrong", "delete"]},
    {"char": "➕", "name": "plus sign", "keywords": ["add", "math"]},
    {"char": "➖", "name": "minus sign", "keywords": ["subtract", "math"]},
    {"char": "➗", "name": "division sign", "keywords": ["divide", "math"]},
    {"char": "‼️", "name": "double exclamation mark", "keywords": ["bang", "surprise", "alert"]},
    {"char": "⁉️", "name": "exclamation question mark", "keywords": ["what", "surprise", "confused"]},
    {"char": "❓", "name": "question mark", "keywords": ["what", "help", "ask"]},
    {"char": "❔", "name": "white question mark", "keywords": ["what", "help", "ask"]},
    {"char": "❕", "name": "white exclamation mark", "keywords": ["wow", "surprise"]},
    {"char": "❗", "name": "exclamation mark", "keywords": ["wow", "surprise", "alert"]},
    {"char": "⚠️", "name": "warning", "keywords": ["alert", "danger", "caution"]},
    {"char": "⛔", "name": "no entry", "keywords": ["stop", "forbidden"]},
    {"char": "🚫", "name": "prohibited", "keywords": ["stop", "forbidden", "no"]},
    {"char": "🛑", "name": "stop sign", "keywords": ["stop", "halt"]},
    {"char": "♻️", "name": "recycling symbol", "keywords": ["recycle", "environment", "green"]},
    {"char": "🚩", "name": "triangular flag", "keywords": ["red flag", "marker"]},
]
